POST http://localhost:5200/api/model4
Content-Type: application/json

{    
    "ageAtStart": 55,    
    "amountAtStart": 400000,
    "annualContribution": 24000,
    "allocations": [
        {
            "name": "Growth",
            "proportion": 0.8,
            "meanAnnualReturn": 0.05,
            "standardDeviation": 0.25
        },
        {
            "name": "MinimalRisk",
            "proportion": 0.2,
            "meanAnnualReturn": 0,
            "standardDeviation": 0
        }
    ],
    "targetAge": 67,
    "iterations": 3,
    "randomSeed": 1
}   
