name: Build and test api
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: code/dotnet/Api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Adjust to your .NET version

    - name: Restore dependencies
     
      run: dotnet restore

    - name: Build
      working-directory: code/dotnet/Api
      run: dotnet build --configuration Release --no-restore Api.csproj

    # - name: Run tests
    #   run: dotnet test --no-restore --verbosity normal