name: frontend

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4

        with:
          node-version: '20.x'
      - run: npm install
        working-directory: code/angular

      - run: npm run build
        working-directory: code/angular

  deploy:
    needs: build

    permissions:
      contents: write
      pages: write     
      id-token: write  

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - run: npm install
        working-directory: code/angular
      - run: npm run build -- --base-href /pension-predictor/
        working-directory: code/angular
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: './code/angular/dist/pension-predictor/browser'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
